### ISSUE TITLE
Traceroute/ICMP extension

### ISSUE THREAD

**Issue by furry13** [furry13/v6ops-464xlat-enable#13]
Add text about traceroite support

**Comment by mstojens** [comment]
This is being worked on here, and we should probably reference at some point: https://github.com/eqvinox/icmpext-clat-source

**Comment by furry13** [comment]
I was going to add some text, but the problem is how to do it w/o making it a normative reference (otherwise this document gets blocked).

I'd suggest to wait and see how quick we can move the int-area one forward before adding a reference here.

**Comment by mstojens** [comment]
Do you want to do an informative reference to the uber-merged draft on this topic? Or just leave this topic up to that draft and say nothing about tracert for IPv4 in claton?

**Comment by furry13** [comment]
Oh I wanted to mention it in our call...So -  https://github.com/eqvinox/icmpext-clat-source depends on another Intarea draft now (see https://datatracker.ietf.org/doc/draft-equinox-v6ops-icmpext-xlat-v6only-source/). So, IMHO, we shall say nothing, :

- draft-equinox-v6ops-icmpext-xlat-v6only-source updates RFC7915, which CLAT must implement anyway. So nothing needs to be say in *our* draft. If/when draft-equinox-v6ops-icmpext-xlat-v6only-source and https://datatracker.ietf.org/doc/draft-ietf-intarea-extended-icmp-nodeid/ are published, all clat implementations shall be updated, no matter what our draft says.

**Comment by mstojens** [comment]
Makes sense to me, closing this issue then.
