### ISSUE TITLE
Define what "session" means in the context of the multi-prefix scenario

### ISSUE THREAD

**Issue by furry13** [furry13/v6ops-464xlat-enable#14]
5 tuples?

**Comment by mstojens** [comment]
So each app's connection within the use of CLAT then. Ok I'll go re-read and see if I can suggest a better term because "session" seems a bit generic -- may as well be specific and mention the 5-tuple directly.

**Comment by furry13** [comment]
Closed by https://github.com/furry13/v6ops-464xlat-enable/pull/21
